---
# setup environment
os: linux
dist: jammy
language: java
jdk: openjdk11

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# execute tests
install:
- sudo curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null && echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null && sudo apt-get update && sudo apt-get install -y jenkins
#- java -jar /usr/lib/jenkins-plugin-manager.jar -p workflow-aggregator pipeline-utility-steps http_request
- sudo java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 enable-plugin -restart workflow-aggregator pipeline-utility-steps http_request
script: sudo java -jar /var/cache/jenkins/war/WEB-INF//var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 groovysh -cp src:/usr/share/jenkins:/usr/share/jenkins/ref/plugins -q vars/*.groovy
