---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: jenkins/jenkins:lts-slim # groovy:3.0-jre11
    resource_class: small
    steps:
    - checkout
    - restore_cache:
        keys:
        - jenkins-devops-libs
    - run:
        name: install jenkins pipeline and pipeline utility steps plugins
        command: jenkins-plugin-cli -p workflow-aggregator pipeline-utility-steps http_request
    - save_cache:
        paths:
        - /usr/share/jenkins/ref/plugins
        key: jenkins-devops-libs
    - run: # may need SO
        name: execute syntax check
        command: /opt/java/openjdk/bin/java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 groovysh -cp src:/usr/share/jenkins:/usr/share/jenkins/ref/plugins -q vars/*.groovy
        no_output_timeout: 45s

workflows:
  execute_tests:
    jobs:
    - test
