---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: jenkins/jenkins:lts-slim # groovy:3.0-jre11
    steps:
    - checkout
    - run:
        name: execute syntax check
        command: groovysh -cp src -q vars/*.groovy
        no_output_timeout: 45s

workflows:
  execute_tests:
    jobs:
    - test
